### ISSUE TITLE
代码跑不起来

### ISSUE THREAD

**Issue by shuqincao** [RomainLITUD/DGCN_traffic_forecasting#2]
OSError: Unable to create file (unable to open file: name = '/pretrained/test.h5', errno = 2, error message = 'No such file or directory', flags 是不是缺少文件 “/pretrained/test.h5”

**Comment by RomainLITUD** [comment]
Hi, shuqincao,

I guess that you are running DGCRNN.ipynb, If you want to load the pre-trained model, just run:

```
file=h5py.File('pretrained/cc2-k4.h5','r')
weight = []
for i in range(len(file.keys())):
    weight.append(file['weight'+str(i)][:])
model.set_weights(weight)
```
This is a dummy way but it works for all keras/tensorflow versions. If you want to train you own model, run:
```
model.compile(loss = rmse,
              optimizer=opt,
              metrics=['mae', 'mape'])

callbacks = [EarlyStopping(monitor='val_loss', patience=5),
             ModelCheckpoint(filepath='\pretrained\test.h5', save_weights_only=True, monitor='val_loss', save_best_only=True),
             ScheduledSampling(k=4)
            ]

history = model.fit([X_train,E_train], Y_train,
          epochs=256,
          batch_size=128,
          callbacks=callbacks,
          #validation_data = ([x_val,e_val], y_val), optional
          shuffle='batch',
          validation_split = 0.2
                   )
```
This does not always works. It depends on your keras/tensorflow/networkx version. But you can also remove callbacks in model.fit and just train it normally.

**Comment by RomainLITUD** [comment]
> OSError: Unable to create file (unable to open file: name = '/pretrained/test.h5', errno = 2, error message = 'No such file or directory', flags 是不是缺少文件 “/pretrained/test.h5”

Hi, shuqincao,

I guess that you are running DGCRNN.ipynb, If you want to load the pre-trained model, just run:

```
file=h5py.File('pretrained/cc2-k4.h5','r')
weight = []
for i in range(len(file.keys())):
    weight.append(file['weight'+str(i)][:])
model.set_weights(weight)
```
This is a dummy way but it works for all keras/tensorflow versions. If you want to train you own model, run:
```
model.compile(loss = rmse,
              optimizer=opt,
              metrics=['mae', 'mape'])

callbacks = [EarlyStopping(monitor='val_loss', patience=5),
             ModelCheckpoint(filepath='\pretrained\test.h5', save_weights_only=True, monitor='val_loss', save_best_only=True),
             ScheduledSampling(k=4)
            ]

history = model.fit([X_train,E_train], Y_train,
          epochs=256,
          batch_size=128,
          callbacks=callbacks,
          #validation_data = ([x_val,e_val], y_val), optional
          shuffle='batch',
          validation_split = 0.2
                   )
```
This does not always works. It depends on your keras/tensorflow/networkx version. But you can also remove callbacks in model.fit and just train it normally.

**Comment by shuqincao** [comment]
Can you provide a DGCRNN file of .py type

**Comment by RomainLITUD** [comment]
This Tensorflow and Keras version is old. Please refer to the PyTorch version of the extended model [here](https://github.com/RomainLITUD/uncertainty-aware-traffic-speed-flow-demand-prediction). Or the online streamlit demo [here](https://nltrafficpredictiondemo-ekpqd7e8sdue92ewyttuuw.streamlit.app/).
